/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 1
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_content_token1 = 1,
  aux_sym_content_token2 = 2,
  anon_sym_POUND = 3,
  anon_sym_POUND2 = 4,
  anon_sym_LBRACE_POUND = 5,
  aux_sym_nelt_expr_token1 = 6,
  anon_sym_POUND_RBRACE = 7,
  anon_sym_LBRACE_LBRACE = 8,
  aux_sym_nelt_val_token1 = 9,
  anon_sym_RBRACE = 10,
  anon_sym_RBRACE_RBRACE = 11,
  anon_sym_LBRACE_LBRACE_DASH = 12,
  sym_template = 13,
  sym_content = 14,
  sym_nelt_tags = 15,
  sym_nelt_expr = 16,
  sym_nelt_val = 17,
  aux_sym_template_repeat1 = 18,
  aux_sym_content_repeat1 = 19,
  aux_sym_nelt_expr_repeat1 = 20,
  aux_sym_nelt_val_repeat1 = 21,
  alias_sym_expr = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_content_token1] = "content_token1",
  [aux_sym_content_token2] = "content_token2",
  [anon_sym_POUND] = "#",
  [anon_sym_POUND2] = "# ",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym_nelt_expr_token1] = "nelt_expr_token1",
  [anon_sym_POUND_RBRACE] = "#}",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [aux_sym_nelt_val_token1] = "nelt_val_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [sym_template] = "template",
  [sym_content] = "content",
  [sym_nelt_tags] = "nelt_tags",
  [sym_nelt_expr] = "nelt_expr",
  [sym_nelt_val] = "nelt_val",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_nelt_expr_repeat1] = "nelt_expr_repeat1",
  [aux_sym_nelt_val_repeat1] = "nelt_val_repeat1",
  [alias_sym_expr] = "expr",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [aux_sym_content_token2] = aux_sym_content_token2,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_POUND2] = anon_sym_POUND2,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym_nelt_expr_token1] = aux_sym_nelt_expr_token1,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [aux_sym_nelt_val_token1] = aux_sym_nelt_val_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [sym_template] = sym_template,
  [sym_content] = sym_content,
  [sym_nelt_tags] = sym_nelt_tags,
  [sym_nelt_expr] = sym_nelt_expr,
  [sym_nelt_val] = sym_nelt_val,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_nelt_expr_repeat1] = aux_sym_nelt_expr_repeat1,
  [aux_sym_nelt_val_repeat1] = aux_sym_nelt_val_repeat1,
  [alias_sym_expr] = alias_sym_expr,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_nelt_expr_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_nelt_val_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_nelt_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_nelt_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_nelt_val] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nelt_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nelt_val_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_expr] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_expr,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_nelt_expr_repeat1, 2,
    aux_sym_nelt_expr_repeat1,
    alias_sym_expr,
  aux_sym_nelt_val_repeat1, 2,
    aux_sym_nelt_val_repeat1,
    alias_sym_expr,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '{') ADVANCE(1);
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '{') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_content_token1);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '#') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(6);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_content_token2);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == '}') ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '}') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_POUND2);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_nelt_expr_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_nelt_expr_token1);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(22);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_nelt_val_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_nelt_val_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_content_token2] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND2] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_POUND_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(19),
    [sym_content] = STATE(2),
    [sym_nelt_tags] = STATE(2),
    [sym_nelt_expr] = STATE(6),
    [sym_nelt_val] = STATE(6),
    [aux_sym_template_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [aux_sym_content_token2] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_POUND2] = ACTIONS(5),
    [anon_sym_LBRACE_POUND] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_content] = STATE(3),
    [sym_nelt_tags] = STATE(3),
    [sym_nelt_expr] = STATE(6),
    [sym_nelt_val] = STATE(6),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(11),
    [aux_sym_content_token1] = ACTIONS(5),
    [aux_sym_content_token2] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_POUND2] = ACTIONS(5),
    [anon_sym_LBRACE_POUND] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_content] = STATE(3),
    [sym_nelt_tags] = STATE(3),
    [sym_nelt_expr] = STATE(6),
    [sym_nelt_val] = STATE(6),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(13),
    [aux_sym_content_token1] = ACTIONS(15),
    [aux_sym_content_token2] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(15),
    [anon_sym_POUND2] = ACTIONS(15),
    [anon_sym_LBRACE_POUND] = ACTIONS(18),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(21),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_content_repeat1,
    ACTIONS(28), 3,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(26), 4,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_POUND,
      anon_sym_POUND2,
  [18] = 4,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_content_repeat1,
    ACTIONS(35), 3,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(32), 4,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_POUND,
      anon_sym_POUND2,
  [36] = 2,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 7,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_POUND,
      anon_sym_POUND2,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [49] = 2,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 7,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_POUND,
      anon_sym_POUND2,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [62] = 2,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 7,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_POUND,
      anon_sym_POUND2,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [75] = 2,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 7,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_POUND,
      anon_sym_POUND2,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [88] = 2,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 7,
      aux_sym_content_token1,
      aux_sym_content_token2,
      anon_sym_POUND,
      anon_sym_POUND2,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [101] = 4,
    ACTIONS(57), 1,
      anon_sym_POUND,
    ACTIONS(59), 1,
      aux_sym_nelt_expr_token1,
    ACTIONS(61), 1,
      anon_sym_POUND_RBRACE,
    STATE(13), 1,
      aux_sym_nelt_expr_repeat1,
  [114] = 4,
    ACTIONS(63), 1,
      aux_sym_nelt_val_token1,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(67), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(14), 1,
      aux_sym_nelt_val_repeat1,
  [127] = 4,
    ACTIONS(57), 1,
      anon_sym_POUND,
    ACTIONS(59), 1,
      aux_sym_nelt_expr_token1,
    ACTIONS(69), 1,
      anon_sym_POUND_RBRACE,
    STATE(15), 1,
      aux_sym_nelt_expr_repeat1,
  [140] = 4,
    ACTIONS(63), 1,
      aux_sym_nelt_val_token1,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(16), 1,
      aux_sym_nelt_val_repeat1,
  [153] = 4,
    ACTIONS(73), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      aux_sym_nelt_expr_token1,
    ACTIONS(79), 1,
      anon_sym_POUND_RBRACE,
    STATE(15), 1,
      aux_sym_nelt_expr_repeat1,
  [166] = 4,
    ACTIONS(81), 1,
      aux_sym_nelt_val_token1,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    ACTIONS(87), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(16), 1,
      aux_sym_nelt_val_repeat1,
  [179] = 2,
    ACTIONS(91), 1,
      aux_sym_nelt_expr_token1,
    ACTIONS(89), 2,
      anon_sym_POUND,
      anon_sym_POUND_RBRACE,
  [187] = 2,
    ACTIONS(93), 1,
      aux_sym_nelt_val_token1,
    ACTIONS(95), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACE_RBRACE,
  [195] = 1,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 49,
  [SMALL_STATE(8)] = 62,
  [SMALL_STATE(9)] = 75,
  [SMALL_STATE(10)] = 88,
  [SMALL_STATE(11)] = 101,
  [SMALL_STATE(12)] = 114,
  [SMALL_STATE(13)] = 127,
  [SMALL_STATE(14)] = 140,
  [SMALL_STATE(15)] = 153,
  [SMALL_STATE(16)] = 166,
  [SMALL_STATE(17)] = 179,
  [SMALL_STATE(18)] = 187,
  [SMALL_STATE(19)] = 195,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nelt_tags, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nelt_tags, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nelt_expr, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nelt_expr, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nelt_val, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nelt_val, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nelt_expr, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nelt_expr, 3, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nelt_val, 3, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nelt_val, 3, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_nelt_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nelt_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_nelt_expr_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nelt_val_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_nelt_val_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_nelt_val_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_nelt_expr_repeat1, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nelt_expr_repeat1, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nelt_val_repeat1, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_nelt_val_repeat1, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nelt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
